### ISSUE TITLE
Non-plugin related Issues

### ISSUE THREAD

**Issue by NoodlesDragon** [buhiroshi0205/RandomUtils#10]
Here are a list of non-plugin related issues that need to be discussed prior to launch of first public release. Please notify for the dismissal of said problems.
### Rank Related
- [ ] Configuring a ranking system for non donor ranks.  
- Autorank?
- Self made requirements?

Configuring the commands available to each rank

-- note: problem dismissed for now; to be implemented in future
- [ ] Feasibility of a 'VIP' or 'scum/shit' rank
- 'VIP' is just like a member rank without any different perks. Given to exclusive friends etc, when ranked up, they rank up to the 2nd available non-donor rank.
- 'Scum' rank is a just-for-laughs rank for stingy ass donors
- [ ] Donor requirements
- Amount of payment?
- Donation platform?
- Recurring fees? Pay once for life, or pay once per month?
- Donor demotion related issues
### Global (Misc)
- [x] Requirement of a censor plugin (for foul language) ?
- [x] Power distribution between the administrative ranks.
- [x] Ban & Appeal platforms
- [x] misc addition of plugins

---

This is by no means a complete list. Thus, more information will be updated later.

wils / noodles

**Comment by buhiroshi0205** [comment]
wtf you can only assign one person!?

**Comment by buhiroshi0205** [comment]
lmao

**Comment by NoodlesDragon** [comment]
Hiroshi why are you being trolled

**Comment by buhiroshi0205** [comment]
nah forget getting trolled. Only autorank is urgent here right

**Comment by buhiroshi0205** [comment]
get on wechat

**Comment by buhiroshi0205** [comment]
Don't think we need this list now. We have other threads and lists and they seem to suffice
