### ISSUE TITLE
Get Wilson to use git and commit code

### ISSUE THREAD

**Issue by buhiroshi0205** [buhiroshi0205/RandomUtils#18]
Heh heh

**Comment by NoodlesDragon** [comment]
Oh

**Comment by buhiroshi0205** [comment]
seems like it's never gonna happen ._.

**Comment by NoodlesDragon** [comment]
Why not

**Comment by buhiroshi0205** [comment]
LMAO do you want to?

**Comment by buhiroshi0205** [comment]
well...

**Comment by NoodlesDragon** [comment]
suh

**Comment by buhiroshi0205** [comment]
Actually the programming load is really light rn so I can deal with it by myself. If the load intensifies then I'll ask you for help again.
