### ISSUE TITLE
Add teleport delays and messages for /shop, /spawn, /hub

### ISSUE THREAD

**Issue by buhiroshi0205** [buhiroshi0205/RandomUtils#5]
To prevent teleporting away to safety

either we can hook this up to the _Essentials_ teleport system or self-program it.

**Comment by buhiroshi0205** [comment]
current idea: change the mechanics of these commands to
Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "sudo " + p.getName()/\* + command */)
I know this is a very bad programming logic, but hey it is easy and it works like a charm!

**Comment by zhuyifei1999** [comment]
Let's _not_ do this

**Comment by buhiroshi0205** [comment]
...... It's necessary, bad code or good code (essentials API hook)

**Comment by buhiroshi0205** [comment]
whelp, just did exactly that. The bad code is in.
